### ISSUE TITLE
Warm/Cold brightness ratio

### ISSUE THREAD

**Issue by mergen3107** [calin-darie/gentle-glow-onyx-boox#10]
Hi!

Currently GentleGlow's `Brightness` increases both of the `white` and `warm` light levels with equal increments.

However, on the Onyx Boox Kon-Tiki 2 (or Nova 3), there are 9 cold light LEDs and 8 warm light LEDs in between them.
Therefore, the levels of the `Brightness` should be in appropriate ratio in order to keep the overall color temperature.

So for each 1 point of cold level, there should be 9/8 = 1.125 levels of warm. I don't know how you do the math, but you could probably do `floor` on a fixed scale so that this accumulated discrepancy will be kept. For example, for each `10/20/30/...` cold levels, there should be `11/22/34/...` warm levels.

With the current code, color gets shifted toward cold as the `Brightness` goes up.

**Comment by calin-darie** [comment]
Hi!

Hmm this one is tricky. I suppose that all the 9 cold LEDs light up even at the lowest brightness, they just receive a very low voltage.. Same with the 8 warm LEDs. I don't think the ninth cold LED is gradually being deployed as one cranks up the brightness. So rather than the plain number of LEDs maybe the issue is a different curve of the brightness-given-voltage function? With the cold LEDs maybe this curve is steeper.

One quick - and potentially wrong - way to test my hypothesis would be for you to lock warm and cold together in the native sliders and see if the color is still shifting. And is it consistently shifting towards cold, or do warm and cold even out when you reach max? I say potentially wrong, because Onyx keep a table for each set of lights to associate a slider position to a brightness value. And the values in the tables might differ if they attemptempted some kind of calibration.  Now what I'm curious about is: did they do this calibration per model - series level - , or per device - unit level -?

I might have to gather the warmth & cold brightness tables as well as temperature measurements - or at least subjective impressions, although I'm sure that different people will have different sensitivities to each kind of light - from multiple devices of each series before I can come up with a generic solution. And even then the conclusion may be that the results are too haphazard to draw a conclusion. Maybe we need a manual calibration feature and let everybody figure it out for themselves?

So this one is tricky.

**Comment by mergen3107** [comment]
Thank you for your details answer!
I did `logcat *:S McCTMBrightnessController` with `grep` for `white` and `warm` side by side and here are findings. 

1) When both lights start from the maximum and get adjusted while locked, they have the same value expect for the middle part. There it gets slightly colder and then equalizes again:
![image](https://user-images.githubusercontent.com/6279855/132404485-239f8316-007c-44f9-aa34-51a012c155ee.png)


2) When the warmth is set so some value (a larger one in this case), the light gets slightly colder by the time the warmth reaches its maximum. This is seen by the delta between warm and white:
![image](https://user-images.githubusercontent.com/6279855/132404435-21eb5060-7abc-4990-8fa8-e262526875ce.png)

This is only noticeable by the naked eye when adjusting the light at night, in the dark.

Is there a way I can find the lights table? I have root access, so I could probably get some apk or jar files to look.

**Comment by mergen3107** [comment]
So from (2), it looks like Onyx is using some sort of compensation of warm when the lights are adjusted in the locked position. 
May this is why I noticed difference between Onyx control and your `Brightness`.

**Comment by calin-darie** [comment]
You've just found the lights table, empirically. It's table (1). I didn't know the values were logged.

I conclude from (1) that 
* Apart from the slight variations mid-range, there's no attempt from Onyx to compensate for a difference in output between warm and cold LEDs. I expect Gentle Glow with Warmth 50 starting at brightness 100 down to 0 to behave similarly: except mid-range, warm and cold values are equal and if there's a shift in temperature then it happens for both the Onyx controls and Gentle Glow's
* There is no difference between table (1) on Nova 3 vs on my old Note Pro. So they probably didn't customize the values between series, let alone per-device calibration.

**Comment by calin-darie** [comment]
On my Note Pro with firmware 3.1_302 (2021-06-28 16:19) they still don't allow locking at different levels, so I can't test that.  What firmware did you use to obtain (2)? And did I understand correctly, do they offer locking at different levels now?

What I can say is that if you look at the ratio instead of the delta, you'll see they don't do any compensation:
<html>
<body>
<google-sheets-html-origin>

cold | warm | cold / warm
-- | -- | --
105 | 180 | 0.5833333333
115 | 185 | 0.6216216216
120 | 190 | 0.6315789474
125 | 195 | 0.641025641
130 | 205 | 0.6341463415
135 | 210 | 0.6428571429
140 | 215 | 0.6511627907
145 | 220 | 0.6590909091
150 | 230 | 0.652173913
155 | 240 | 0.6458333333
160 | 245 | 0.6530612245
165 | 255 | 0.6470588235


</body>
</html>

The slight variations come only from the constraint of falling on one of the 32 predefined increments in table (1) - 33 if you also count )cold: 0, warm: 0).

**Comment by calin-darie** [comment]
With Gentle Glow is I chose to sacrifice warmth consistency in favor of a wider brightness range. As a result, sometimes the required warmth to keep the cold / warm ratio is either less than 5 - which is the minimum value that consistently turns on the leds on their lowest setting, so Gentle Glow has to approximate to either 0 or 5 or greater than 255, so Gentle Glow approximates to 255. This becomes more apparent the more extreme the ratio is, towards the ends of the brightness range. You can set say warmth 4 or 96 and play with the brightness slider.

My best guess is that you were experiencing these rounding glitches, that result from the tradeoff I chose.

**Comment by mergen3107** [comment]
>  What firmware did you use to obtain (2)?

Kon-Tiki 2 has recent firmware based on `3.0`, according to its fingerprint `getprop | grep finger`:
```
[ro.bootimage.build.fingerprint]: [ONYX/Kon_Tiki2/Kon_Tiki2:10/2021-07-22_16-01_3.0-mc_874249874/2389:user/dev-keys]
```


> And did I understand correctly, do they offer locking at different levels now?

I don't know about stock FW on Kon-Tiki 2, but current FW allows me to lock different levels, yes.



> if you look at the ratio instead of the delta, you'll see they don't do any compensation

Ah, OK!



> My best guess is that you were experiencing these rounding glitches, that result from the tradeoff I chose.

OK! Thank you very much for your detailed explanation :)

**Comment by calin-darie** [comment]
> When the warmth is set so some value (a larger one in this case), the light gets slightly warmer by the time the warmth reaches its maximum. This is seen by the delta between warm and white:

I tried to take that into account. When writing the math for Gentle Glow, I've done some measurements on brightness. On one hand, they were performed with the phone's light sensor, so take them with a grain of salt, on the other hand I could get consistent results. The measurements indicate that brightness varies *exponentially* with the brightness setting - value on you charts - so in order to keep the warmth stable you have to alter the ratio. If you keep the ratio constant as Onyx does you end up shifting towards the dominant color, so in your case more warm light in the mix => light gets warmer as you turn them up locked together with a constant ratio.

Now do you think my measurements are off and I tend to overcompensate for the exponential curve? If so, do you have access to a better brightness measurement setup?

So before we close this issue: can you confirm that warmth stays roughly the same except for some edge cases near the end of the brightness & warmth ranges?

**Comment by mergen3107** [comment]
> The measurements indicate that brightness varies _exponentially_ with the brightness setting - value on you charts - so in order to keep the warmth stable you have to alter the ratio.

I actually forgot about this! Thank you for reminding. 



> Now do you think my measurements are off and I tend to overcompensate for the exponential curve?

No, it turns out your approach seems more accurate to the color temperature. I just mentioned that I saw difference between your approach and Onyx stock app. 



> So before we close this issue: can you confirm that the perceived warmth stays roughly the same except for some edge cases near the end of the brightness & warmth ranges?

Yes, except very bright cases and very dim cases (which are harder to judge) the color stays about the same as the Brightness is adjusted, looking by a naked eye. I just don’t have proper color light sensors to actually test that :)

Thank you for all your explanations :)
